### ISSUE TITLE
Fix tests for sharded_cluster

### ISSUE THREAD

**Issue by johnnyshields** [tablecheck/mongoid-ultra#16]
See: https://github.com/tablecheck/mongoid-ultra/actions/runs/4664431260/jobs/8256670324?pr=15

```
  41) Mongoid::QueryCache after calling none? on an association returns all children for the association
      Failure/Error: raise "Session registry contains live sessions: #{sessions.join(', ')}"
      
      RuntimeError:
        Session registry contains live sessions: #<Mongo::Session:0x00007f7aa6f5b838>
      # ./spec/shared/lib/mrss/session_registry.rb:61:in `verify_sessions_ended!'
      # ./spec/mongoid/query_cache_spec.rb:24:in `block (2 levels) in <top (required)>'
      # ./spec/mongoid/query_cache_spec.rb:10:in `block (3 levels) in <top (required)>'
      # ./lib/mongoid/query_cache.rb:47:in `cache'
      # ./spec/mongoid/query_cache_spec.rb:10:in `block (2 levels) in <top (required)>'
      # ./spec/lite_spec_helper.rb:74:in `block (3 levels) in <top (required)>'
      # ./spec/lite_spec_helper.rb:73:in `block (2 levels) in <top (required)>'
```
